services:
  svr_n8n:
    image: n8nio/n8n
    container_name: svc-n8n
    restart: always
    environment:
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_EDITOR_BASE_URL=${EXTERNAL_IP}
      - WEBHOOK_URL=${EXTERNAL_IP}
      - N8N_DEFAULT_BINARY_DATA_MODE=filesystem
    ports:
      - "80:5678"
    volumes:
      - /home/ubuntu/n8n-data:/home/node/.n8n
